const datas = [
  
    {
      "id": 1,
      "title": "Highlander Men's Checked Shirt",
      "category": "Men",
      "type": "Shirt",
      "brand": "Highlander",
      "price": 899,
      "rating": 4.3,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980735640/660/HLSH015692_1.JPG",
      "description": "This stylish checked shirt from Highlander is made with premium cotton for comfort and breathability. Perfect for casual outings and daily wear."
    },
    {
      "id": 2,
      "title": "Men's Oversized Printed T-Shirt",
      "category": "Men",
      "type": "T-Shirt",
      "brand": "Ketch",
      "price": 499,
      "rating": 4.1,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/HLTS006683_1.JPG",
      "description": "Stay on top of the streetwear trend with this oversized printed T-shirt. Bold prints and a relaxed fit make it perfect for casual days."
    },
    {
      "id": 3,
      "title": "Men's Ripped Skinny Jeans",
      "category": "Men",
      "type": "Jeans",
      "brand": "Locomotive",
      "price": 1299,
      "rating": 4.5,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980383582/660/PHJN000111_n2.jpg",
      "description": "These ripped skinny jeans from Locomotive add an edgy look. Stretchable denim ensures a comfortable fit while making a bold statement."
    },
    {
      "id": 4,
      "title": "Women's Floral Maxi Dress",
      "category": "Women",
      "type": "Dress",
      "brand": "Tokyo Talkies",
      "price": 1199,
      "rating": 4.4,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8909107209953/660/TTJ6010439_3.jpg",
      "description": "Embrace feminine elegance with this floral maxi dress. Its flowy silhouette and vibrant print make it perfect for brunches and casual parties."
    },
    {
      "id": 5,
      "title": "Women's Straight Kurta",
      "category": "Women",
      "type": "Kurta",
      "brand": "Vishudh",
      "price": 899,
      "rating": 4.2,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905404209191/660/VNKU011358_6.jpg",
      "description": "This straight kurta from Vishudh combines subtle prints and classic cuts, making it ideal for office wear or family gatherings."
    },
    {
      "id": 6,
      "title": "Hoop Boys Printed T-Shirt",
      "category": "Kids",
      "type": "T-Shirt",
      "brand": "Hoop",
      "price": 399,
      "rating": 4.1,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980273685/660/HLTS004155_1.JPG",
      "description": "Keep your little one comfortable with this soft cotton printed T-shirt. Ideal for play and daily adventures."
    },
    {
      "id": 7,
      "title": " Men's Bomber Jacket",
      "category": "Men",
      "type": "Jacket",
      "brand": "Highlander",
      "price": 1599,
      "rating": 4.6,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8909107104388/660/HLJK001065_2.jpg",
      "description": "This sleek bomber jacket from Highlander offers warmth and style. Perfect for casual outings and evening events during winter."
    },
    {
      "id": 8,
      "title": " Women's Crop Top",
      "category": "Women",
      "type": "Top",
      "brand": "Tokyo Talkies",
      "price": 499,
      "rating": 4.0,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8909107075091/660/TTCT000578_2.JPG",
      "description": "This trendy crop top adds a playful touch to your wardrobe. Perfect for casual outings and party nights."
    },
    {
      "id": 9,
      "title": "Ketch Men's Joggers",
      "category": "Men",
      "type": "Trousers",
      "brand": "Ketch",
      "price": 799,
      "rating": 4.2,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980334317/660/PHTR000030_1.jpg",
      "description": "These versatile joggers from Ketch offer a great fit for lounging, workouts, or casual errands."
    },
    {
      "id": 10,
      "title": "Hoop Girls Cotton Night Suit",
      "category": "Womens",
      "type": "Nightwear",
      "brand": "Hoop",
      "price": 699,
      "rating": 4.3,
      "image": "https://kahva.in/cdn/shop/files/DSC_6425.jpg?v=1731409438&width=1540",
      "description": "This cotton night suit for kids offers both comfort and fun with playful prints, making bedtime a joyful experience."
    },
    {
      "id": 11,
      "title": "Roadster Men's Solid Casual Shirt",
      "category": "Men",
      "type": "Shirt",
      "brand": "Roadster",
      "price": 999,
      "rating": 4.4,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/HLSH022618_2.JPG",
      "description": "This solid casual shirt from Roadster is perfect for a sharp, classic look. Great for office wear and casual outings."
    },
    {
      "id": 12,
      "title": "H&M Men's Slim Fit Chinos",
      "category": "Men",
      "type": "Trousers",
      "brand": "H&M",
      "price": 1499,
      "rating": 4.5,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/PHTR000284_2.JPG",
      "description": "Upgrade your wardrobe with these slim-fit chinos from H&M. Ideal for both formal and casual occasions."
    },
    {
      "id": 13,
      "title": "Levis Women's Skinny Fit Jeans",
      "category": "Women",
      "type": "Jeans",
      "brand": "Levis",
      "price": 1999,
      "rating": 4.6,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980297483/660/PTJN000058_2.jpg",
      "description": "These skinny fit jeans from Levis are tailored to flatter your silhouette while providing ultimate comfort."
    },
    {
      "id": 14,
      "title": "Biba Women's Anarkali Kurta",
      "category": "Women",
      "type": "Kurta",
      "brand": "Biba",
      "price": 1899,
      "rating": 4.7,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/52360001506773/660/VNKU006027_2.JPG",
      "description": "This Anarkali Kurta from Biba features rich prints and vibrant colors, perfect for festive occasions."
    },
    {
      "id": 15,
      "title": "Max Boys Denim Shorts",
      "category": "Kids",
      "type": "Shorts",
      "brand": "Max",
      "price": 499,
      "rating": 4.2,
      "image": "https://pictures.kartmax.in/cover/live/600x800/quality=6/sites/aPfvUDpPwMn1ZadNKhP7/product-images/8905980291740/660/HLCE000009_1.JPG",
      "description": "These denim shorts from Max are ideal for playdates and everyday adventures. Stylish and comfy for your little boy."
    },
    {
      "id": 16,
      "title": "H&M Girls Sleeveless Party Dress",
      "category": "Kids",
      "type": "Dress",
      "brand": "H&M",
      "price": 1199,
      "rating": 4.4,
      "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSvPDllqCK6L7swX7ykWU7aANGo_hUoXp5XE74F8CI_hKdynD4ux3EzXTps8xySIsxngxywMhMVOmVthsnvRc5FflmO5t_ylri4pTkmkpC6iL8VOfti9KD8WNZfpRMeud8TkIi27rY6vg&usqp=CAc",
      "description": "This sleeveless party dress for girls by H&M will make her feel like a princess. Perfect for birthday parties and festive occasions."
    },
    {
      "id": 17,
      "title": "HRX Men's Training Shorts",
      "category": "Men",
      "type": "Shorts",
      "brand": "HRX",
      "price": 699,
      "rating": 4.3,
      "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRHQvRBEJ7ILu1-cq4hhFOr4bQaSaRdBUfK3glfa9cyq_9oQ6tq3q9xITeh0QgJYpTerl0Rv3W5fGlwFi54Us8YL-OH1S94imduSrChyiBlsL3Pz6QAGAWPVwfile:///var/folders/1b/fcz94qx54wq7v60x7r5l3g8c0000gn/T/TemporaryItems/NSIRD_screencaptureui_eyw5uR/Screenshot%202025-05-14%20at%202.34.07%E2%80%AFPM.png",
      "description": "These lightweight training shorts from HRX are designed for comfort and agility during workouts."
    },
    {
      "id": 18,
      "title": "Only Women's Graphic T-Shirt",
      "category": "Women",
      "type": "T-Shirt",
      "brand": "Only",
      "price": 699,
      "rating": 4.1,
      "image": "https://via.placeholder.com/300",
      "description": "This graphic T-shirt from Only is stylish and perfect for pairing with jeans or shorts for a casual look."
    },
    {
      "id": 19,
      "title": "Zara Women's Satin Skirt",
      "category": "Women",
      "type": "Skirt",
      "brand": "Zara",
      "price": 2499,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "This luxe satin skirt from Zara adds elegance to any outfit, ideal for office parties or dinner dates."
    },
    {
      "id": 20,
      "title": "Adidas Boys Sports T-Shirt",
      "category": "Kids",
      "type": "T-Shirt",
      "brand": "Adidas",
      "price": 799,
      "rating": 4.3,
      "image": "https://via.placeholder.com/300",
      "description": "This sports T-shirt from Adidas will keep your boy stylish and active during school sports or casual play."
    },
    {
      "id": 21,
      "title": "Pepe Jeans Men's Hoodie",
      "category": "Men",
      "type": "Hoodie",
      "brand": "Pepe Jeans",
      "price": 1799,
      "rating": 4.4,
      "image": "https://via.placeholder.com/300",
      "description": "Stay warm and stylish with this cozy hoodie by Pepe Jeans. Perfect for cold weather or casual outings."
    },{
      "id": 22,
      "title": "Adidas Women's Running Shoes",
      "category": "Women",
      "type": "Shoes",
      "brand": "Adidas",
      "price": 3499,
      "rating": 4.7,
      "image": "https://via.placeholder.com/300",
      "description": "These Adidas running shoes provide support and comfort for long-distance runs. A perfect choice for active women."
    },
    {
      "id": 23,
      "title": "Puma Men's Sporty Jacket",
      "category": "Men",
      "type": "Jacket",
      "brand": "Puma",
      "price": 2999,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "Stay comfortable and stylish with this sporty jacket from Puma, perfect for outdoor activities and casual outings."
    },
    {
      "id": 24,
      "title": "Fubu Men's Cargo Shorts",
      "category": "Men",
      "type": "Shorts",
      "brand": "Fubu",
      "price": 899,
      "rating": 4.3,
      "image": "https://via.placeholder.com/300",
      "description": "These cargo shorts by Fubu offer ample storage space with a relaxed fit, making them ideal for casual and outdoor wear."
    },
    {
      "id": 25,
      "title": "H&M Women's Silk Blouse",
      "category": "Women",
      "type": "Blouse",
      "brand": "H&M",
      "price": 1299,
      "rating": 4.6,
      "image": "https://via.placeholder.com/300",
      "description": "This silk blouse from H&M adds a touch of elegance to any outfit. Its light fabric makes it perfect for office wear or evening outings."
    },
    {
      "id": 26,
      "title": "Decathlon Boys Active Hoodie",
      "category": "Kids",
      "type": "Hoodie",
      "brand": "Decathlon",
      "price": 899,
      "rating": 4.4,
      "image": "https://via.placeholder.com/300",
      "description": "This active hoodie from Decathlon is perfect for your little one’s outdoor activities. Comfortable and durable for every adventure."
    },
    {
      "id": 27,
      "title": "Superdry Men's T-Shirt",
      "category": "Men",
      "type": "T-Shirt",
      "brand": "Superdry",
      "price": 1199,
      "rating": 4.6,
      "image": "https://via.placeholder.com/300",
      "description": "This classic T-shirt from Superdry features a bold logo and soft cotton fabric, making it perfect for casual wear."
    },
    {
      "id": 28,
      "title": "Zara Women's Satin Top",
      "category": "Women",
      "type": "Top",
      "brand": "Zara",
      "price": 1699,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "This satin top from Zara adds a luxurious touch to your wardrobe, perfect for both office and evening wear."
    },
    {
      "id": 29,
      "title": "H&M Men's Chinos",
      "category": "Men",
      "type": "Trousers",
      "brand": "H&M",
      "price": 1499,
      "rating": 4.4,
      "image": "https://via.placeholder.com/300",
      "description": "These slim-fit chinos from H&M are versatile and stylish, perfect for both casual and semi-formal occasions."
    },
    {
      "id": 30,
      "title": "Max Boys T-Shirt",
      "category": "Kids",
      "type": "T-Shirt",
      "brand": "Max",
      "price": 499,
      "rating": 4.3,
      "image": "https://via.placeholder.com/300",
      "description": "This soft cotton T-shirt from Max is perfect for your little one’s everyday wear, featuring a playful design."
    },
    {
      "id": 31,
      "title": "Roadster Men's Polo T-Shirt",
      "category": "Men",
      "type": "T-Shirt",
      "brand": "Roadster",
      "price": 899,
      "rating": 4.2,
      "image": "https://via.placeholder.com/300",
      "description": "This classic polo T-shirt from Roadster offers a stylish yet casual look, perfect for weekend outings."
    },
    {
      "id": 32,
      "title": "Biba Women's Kurti",
      "category": "Women",
      "type": "Kurti",
      "brand": "Biba",
      "price": 1299,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "This colorful kurti from Biba features intricate designs, perfect for family gatherings and festive events."
    },
    {
      "id": 33,
      "title": "Fossil Men's Watch",
      "category": "Men",
      "type": "Watch",
      "brand": "Fossil",
      "price": 4999,
      "rating": 4.7,
      "image": "https://via.placeholder.com/300",
      "description": "This stylish Fossil watch combines modern design with classic elements, making it a great accessory for any occasion."
    },
    {
      "id": 34,
      "title": "Van Heusen Women's Formal Shirt",
      "category": "Women",
      "type": "Shirt",
      "brand": "Van Heusen",
      "price": 1599,
      "rating": 4.6,
      "image": "https://via.placeholder.com/300",
      "description": "This formal shirt from Van Heusen is perfect for office wear, with its sleek design and crisp fabric."
    },
    {
      "id": 35,
      "title": "Decathlon Boys Sports Shorts",
      "category": "Kids",
      "type": "Shorts",
      "brand": "Decathlon",
      "price": 599,
      "rating": 4.2,
      "image": "https://via.placeholder.com/300",
      "description": "These sporty shorts from Decathlon are made for active kids. Ideal for both sports and casual activities."
    },
    {
      "id": 36,
      "title": "Nike Men's Sports T-Shirt",
      "category": "Men",
      "type": "T-Shirt",
      "brand": "Nike",
      "price": 1399,
      "rating": 4.7,
      "image": "https://via.placeholder.com/300",
      "description": "This performance-driven Nike sports T-shirt offers breathability and comfort for your workout sessions."
    },
    {
      "id": 37,
      "title": "Jack & Jones Men's Hoodie",
      "category": "Men",
      "type": "Hoodie",
      "brand": "Jack & Jones",
      "price": 2499,
      "rating": 4.4,
      "image": "https://via.placeholder.com/300",
      "description": "This cozy hoodie from Jack & Jones offers warmth and style, perfect for winter casual wear."
    },
    {
      "id": 38,
      "title": "H&M Women's Jumpsuit",
      "category": "Women",
      "type": "Jumpsuit",
      "brand": "H&M",
      "price": 1999,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "This stylish jumpsuit from H&M is a versatile piece for both day and evening wear, with a flattering cut."
    },
    {
      "id": 39,
      "title": "Levis Men's Jeans",
      "category": "Men",
      "type": "Jeans",
      "brand": "Levis",
      "price": 2499,
      "rating": 4.7,
      "image": "https://via.placeholder.com/300",
      "description": "Levis' iconic jeans offer a perfect fit with superior quality denim, making them a wardrobe staple."
    },
    {
      "id": 40,
      "title": "Max Girls Dress",
      "category": "Kids",
      "type": "Dress",
      "brand": "Max",
      "price": 1299,
      "rating": 4.5,
      "image": "https://via.placeholder.com/300",
      "description": "This beautiful dress from Max features colorful patterns, making it perfect for parties and family events."
    }
];

  export default datas;
     
